version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: doc/conf.py

python:
  install:
      - requirements: doc/requirements.txt
      - method: pip
        path: .
  system_packages: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
