version: 2

sphinx:
  configuration: doc/conf.py

python:
    version: 3.6
    install:
        - requirements: doc/requirements.txt
        - requirements: requirements.txt
        - method: pip
          path: .
    system_packages: true

build:
    image: latest
