version: 2

sphinx:
  configuration: doc/conf.py

python:
  install:
      - requirements: doc/requirements.txt
      - method: pip
        path: .

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
